### ISSUE TITLE
Python 3.8 AttributeError: 'function' object has no attribute 'im_func'

### ISSUE THREAD

**Issue by smarie** [smarie/python-autoclass#43]
This seems to happen with autodict on python 3.8 ? Git it from a log in valid8, did not yet reproduce it explicitly

**Comment by beepsoft** [comment]
I can also confirm that autoclass doesn't work with python 3.8 and 3.9, only 3.7. @smarie do you plan to release autoclass for newer python versions?

**Comment by smarie** [comment]
Hello @beepsoft ! My only problem with this is that I did not yet migrate autoclass to github actions as I did for most of my other libs. Until this is done, would [`pyfields`](https://smarie.github.io/python-pyfields/) cover your needs, or is there something really specific to autoclass that you need ?
